version: 2
jobs:
  build:
    docker:
     - image: circleci/python:3.6.1
     - image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: run tests
          command: |
            sleep 5
            python runtests.py

      # Upload coverage report
      # - run:
      #     name: Update coverage
      #     command: |
      #       codecov
      #     when: on_success

      - store_artifacts:
          path: .coverage
