version: 2
jobs:
  build:
    docker:
     - image: circleci/python:3.6.1
     - image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements_test.txt" }}-2
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements_test.txt" }}-2
        
      # run tests!
      - run:
          name: run tests
          command: |
            sleep 5
            pip install -r requirements_test.txt
            python runtests.py

      - store_artifacts:
          path: .coverage
