version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      - run: 
          name: 'install elasticsearch'
          command: |
            docker run -d -e 'discovery.type=single-node' -e 'xpack.security.enabled=false' -p 9200:9200 -p 9300:9300 docker.elastic.co/elasticsearch/elasticsearch:6.1.1

      - run:
          name: run tests
          command: |
            python setup.py test

      # Upload coverage report
      - run:
          name: Update coverage
          command: |
            codecov
          when: on_success

      - store_artifacts:
          path: .coverage

