version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: 'install dependencies'
          command: |
            echo "deb http://http.us.debian.org/debian/ jessie-backports main" | sudo tee -a /etc/apt/sources.list
            echo "deb-src http://http.us.debian.org/debian/ jessie-backports main" | sudo tee -a  /etc/apt/sources.list
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install -t jessie-backports openjdk-8-jre openjdk-8-jre-headless

      - run: 
          name: 'install elasticsearch'
          command: |
            wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.1.deb
            sha1sum elasticsearch-5.6.1.deb
            sudo dpkg -i elasticsearch-5.6.1.deb

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "requirements_test.txt" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      # - run:
      #     name: install dependencies
      #     command: |
      #       python3 -m venv venv
      #       . venv/bin/activate
      #       pip install tox

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "requirements_test.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            sudo /etc/init.d/elasticsearch start
            sleep 7
            python setup.py test

      # Upload coverage report
      - run:
          name: Update coverage
          command: |
            . venv/bin/activate
            codecov
          when: on_success

      - store_artifacts:
          path: .coverage

